image: docker:latest

# When using dind, use the overlayfs driver.
variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
- build
- release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/avluis/iroffer:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.avnet.ws/avluis/iroffer:latest

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  stage: build
  tags:
    - dind
    - ubuntu

release-image:
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  stage: release
  only:
    - master
  tags:
    - dind
    - ubuntu
