image: docker:latest

# When using dind, use the overlayfs driver.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  REGISTRY_SECURE_IMAGE: $CI_REGISTRY/avluis/iroffer:$CI_COMMIT_REF_NAME
  REGISTRY_INTERNAL_IMAGE: $INT_REGISTRY/avluis/iroffer:$CI_COMMIT_REF_NAME
  REGISTRY_PUBLIC_IMAGE: $PUB_REGISTRY/avluis/iroffer:$CI_COMMIT_REF_NAME

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  script:
    - echo "Building the app"
    - docker build --pull -t $REGISTRY_SECURE_IMAGE .
    - docker push $REGISTRY_SECURE_IMAGE
  stage: build
  tags:
    - dind
    - ubuntu

deploy_staging:
  script:
    - echo "Deploy to staging server"
    - docker pull $REGISTRY_SECURE_IMAGE
    - docker tag $REGISTRY_SECURE_IMAGE $REGISTRY_INTERNAL_IMAGE
    - docker push $REGISTRY_INTERNAL_IMAGE
  stage: deploy
  environment:
    name: staging
    url: https://avnet.ws:5001/repository/avluis/iroffer
  only:
    - master
  tags:
    - dind
    - ubuntu

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://hub.docker.com/r/avluis/iroffer
  when: manual
  only:
    - master