#!/usr/bin/with-contenv bash

# create folders
if [ ! -d "${IROFFER_FILES_DIR}" ]; then \
mkdir -p "${IROFFER_FILES_DIR}"
chown -R abc:abc /config
fi

# check file permissions
PUID=${PUID:-911}
if [ ! "$(stat -c %u /config/files)" = "$PUID" ]; then
	echo "Change in ownership detected, please be patient while we chown existing files"
	echo "This could take some time"
	chown abc:abc -R \
	/config/files
fi

# permissions (non-recursive) on config root and folders
chown abc:abc \
	/config \
	/config/*